dotfiles_dir = "dotfiles"

gpg_user_id = "Jesse Hamer <jesse.a.l.hamer@gmail.com>"

import = [
  { path = "browser/browser.toml" },
  { path = "cli/cli.toml" },
  { path = "editor/editor.toml" },
  { path = "git/git.toml" },
  { path = "linux/linux.toml" },
  { path = "music/music.toml" },
  { path = "python/python.toml" },
  { path = "shell/shell.toml" },
  { path = "terminal/terminal.toml" },
]

[settings]
vars = ["vars.toml"]

[profiles.desktop]
extra_profiles = [
  "browser-zen",
  "cli-go",
  "cli-node_js",
  "cli-rust",
  "cli-other",
  "editor-astro_nvim",
  # "editor-kickstart_nvim",
  "git",
  "linux-pop_os",
  "music-youtube_music",
  "python-3_12",
  "shell-bash",
  "shell-sh",
  "shell-zsh",
  "shell-multi",
  "terminal-wezterm",
]
