export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH=$HOME/.config/zsh

# must configure eza plugin before loading it
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'header' yes
zstyle ':omz:plugins:eza' 'dirs-first' yes

# Configure antigen
export ADOTDIR=$HOME/.antigen
export ANTIGEN_LOG=$ADOTDIR/antigen.log

# Define path to antigen repo
export ANTIGEN_PATH=$HOME/package-repos/antigen

# source antigen and load plugins
source $ANTIGEN_PATH/antigen.zsh
antigen init .antigenrc

# configure fast-syntax-highlighting theme
fast-theme XDG:catppuccin-macchiato


# source zsh/custom files
source $ZSH/aliases.zsh
source $ZSH/bat.zsh
source $ZSH/completions.zsh
source $ZSH/exports.zsh
source $ZSH/micromamba.zsh

source $HOME/.rvm/scripts/rvm
source $HOME/.cargo/env


