[project]
name = "neovim-nightly"
version = "0.1.0"
description = "Environment for Neovim Nightly Python provider."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=25.0",
    "pynvim>=0.5.2",
]
