[profiles.system-pop_os.dots]
gtk3 = { source = "system/gtk/gtk-3.0", target = ".config/gtk-3.0" }
gtk4 = { source = "system/gtk/gtk-4.0", target = ".config/gtk-4.0" }
qt5ct = { source = "system/qt/qt5ct", target = ".config/qt5ct" }
xdg-dirs = { source = "system/xdg/user-dirs.dirs", target = ".config/user-dirs.dirs" }
xdg-locale = { source = "system/xdg/user-dirs.locale", target = ".config/user-dirs.locale" }

