[profiles.python-3_12.dots]
ipython-default = { source = "python/ipython/profile_default/ipython_config.py", target = ".ipython/profile_default/ipython_config.py" }
ipython-kernel-default = { source = "python/ipython/profile_default/ipython_kernel_config.py", target = ".ipython/profile_default/ipython_kernel_config.py" }
jupyter-lab = { source = "python/jupyter/lab", target = ".jupyter/lab/user-settings" }
